### ISSUE TITLE
Documentation enhancement: Is LabVIEW restart necessary after install?

### ISSUE THREAD

**Issue by RobustoSystems** [HunterJKI/decoration-properties#5]
This is a tiny, nitpick issue.

At the moment the Readme.md file does not specify whether a LabVIEW restart is necessary.

Before installing the tool manually (by copying the files into the specified locations) I restarted LabVIEW "just in case", and the installation worked perfectly first time. But not sure whether this was necessary.

Perhaps a bullet point could be added in the Readme file to specify whether restart is needed or not.

Thanks,
Petru Tarabuta, Robusto Systems, UK

**Comment by HunterJKI** [comment]
good idea, I updated the read me.
